In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
x = []
len(dir(x))

48

In [5]:
len(dir(n1))

166

In [6]:
n1.shape             #tells number of values 

(4,)

In [7]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linspace
- random.rand
- randon.randn
- random.randint
- eye
- one 
- zeroes

In [8]:
#arange
x = np.arange(-10,10,.2)
x.shape

(100,)

In [9]:
#linspace(linear spacing)
y = np.linspace(1,5,10) #10 is nuumber of elements you want to generate
print(y)
print(y.shape)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
(10,)


In [10]:
#random.rand
np.random.rand(3,3)

array([[0.1782959 , 0.74314354, 0.2160689 ],
       [0.78590061, 0.63453149, 0.49365577],
       [0.03124995, 0.59568047, 0.46890971]])

In [11]:
np.random.randn(10)     #gives random numbers surronding 0 or some other number

array([ 0.83273256, -2.85370744, -0.95864844, -0.11732432, -0.95693312,
        0.46961684,  0.06501283,  1.581265  ,  0.5978135 , -0.13351647])

In [12]:
np.random.randint(1,5,(5,5))  #creates a 5,5 matrix b/w numbers 1 to 5  where 5 is exclusive

array([[3, 4, 2, 2, 3],
       [1, 1, 1, 4, 2],
       [3, 4, 2, 1, 2],
       [3, 3, 4, 3, 4],
       [4, 2, 1, 1, 1]])

In [13]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[4 9]
 [3 4]
 [7 5]]
[[9 2]
 [6 2]
 [5 1]]


In [14]:
x + 5  #adds number to all the numbers of the matrix without the use of loop

array([[ 9, 14],
       [ 8,  9],
       [12, 10]])

In [15]:
x+y

array([[13, 11],
       [ 9,  6],
       [12,  6]])

In [16]:
x * y

array([[36, 18],
       [18,  8],
       [35,  5]])

In [17]:
y.T #transpose

array([[9, 6, 5],
       [2, 2, 1]])

In [18]:
x.dot(y.T)

array([[54, 42, 29],
       [35, 26, 19],
       [73, 52, 40]])

In [19]:
np.sin(x)

array([[-0.7568025 ,  0.41211849],
       [ 0.14112001, -0.7568025 ],
       [ 0.6569866 , -0.95892427]])

In [20]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

32
5.333333333333333
2.0548046676563256
3
9
4.222222222222222


In [24]:
a= np.linspace(0,5,50)
print(a.shape)
a2 = a.reshape(10,5)
print(a2)                  #converting to 2D array
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [25]:
a2.reshape(2,5,5)    #converting in 3D array

array([[[0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327],
        [0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735],
        [1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143],
        [1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551],
        [2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959]],

       [[2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367],
        [3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776],
        [3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184],
        [4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592],
        [4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ]]])

In [28]:
z= np.random.randint(1,10,(10,10))
print(z)

[[6 7 4 1 2 7 8 3 9 6]
 [2 3 4 1 4 3 3 7 6 4]
 [6 2 1 8 1 5 2 5 8 3]
 [7 1 1 8 9 8 2 6 1 2]
 [5 7 6 2 1 1 2 7 7 1]
 [4 7 3 4 2 3 3 5 1 4]
 [3 4 1 4 2 9 8 1 8 7]
 [3 6 4 5 1 4 5 9 7 2]
 [1 2 3 2 9 5 2 2 2 8]
 [7 6 6 4 9 6 5 6 7 7]]


In [31]:
print(z[0,0])
print(z[0,-1])
print(z[-1,0])
print(z[-1,-1])

6
6
7
7


In [35]:
print(z[0])
print(z[-1])
print(z[:3]) #gives first three rows
print(z[:-3]) #gives last three rows

[6 7 4 1 2 7 8 3 9 6]
[7 6 6 4 9 6 5 6 7 7]
[[6 7 4 1 2 7 8 3 9 6]
 [2 3 4 1 4 3 3 7 6 4]
 [6 2 1 8 1 5 2 5 8 3]]


In [41]:
print(z[:,0])#first column
print(z[:,-1])#last column
print(z[:,:3])#first 3 column
print(z[:,-3:])#last 3 column

[6 2 6 7 5 4 3 3 1 7]
[6 4 3 2 1 4 7 2 8 7]
[[6 7 4]
 [2 3 4]
 [6 2 1]
 [7 1 1]
 [5 7 6]
 [4 7 3]
 [3 4 1]
 [3 6 4]
 [1 2 3]
 [7 6 6]]
[[3 9 6]
 [7 6 4]
 [5 8 3]
 [6 1 2]
 [7 7 1]
 [5 1 4]
 [1 8 7]
 [9 7 2]
 [2 2 8]
 [6 7 7]]


In [42]:
print(z[:,[0,2,3,5]])#gives 0th ,2nd,3rd,5th column

[[6 4 1 7]
 [2 4 1 3]
 [6 1 8 5]
 [7 1 8 8]
 [5 6 2 1]
 [4 3 4 3]
 [3 1 4 9]
 [3 4 5 4]
 [1 3 2 5]
 [7 6 4 6]]


- filtering

In [43]:
z

array([[6, 7, 4, 1, 2, 7, 8, 3, 9, 6],
       [2, 3, 4, 1, 4, 3, 3, 7, 6, 4],
       [6, 2, 1, 8, 1, 5, 2, 5, 8, 3],
       [7, 1, 1, 8, 9, 8, 2, 6, 1, 2],
       [5, 7, 6, 2, 1, 1, 2, 7, 7, 1],
       [4, 7, 3, 4, 2, 3, 3, 5, 1, 4],
       [3, 4, 1, 4, 2, 9, 8, 1, 8, 7],
       [3, 6, 4, 5, 1, 4, 5, 9, 7, 2],
       [1, 2, 3, 2, 9, 5, 2, 2, 2, 8],
       [7, 6, 6, 4, 9, 6, 5, 6, 7, 7]])

In [44]:
z<5    #boolean filter

array([[False, False,  True,  True,  True, False, False,  True, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True, False, False,
         True],
       [False,  True,  True, False,  True, False,  True, False, False,
         True],
       [False,  True,  True, False, False, False,  True, False,  True,
         True],
       [False, False, False,  True,  True,  True,  True, False, False,
         True],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True, False, False,  True, False,
        False],
       [ True, False,  True, False,  True,  True, False, False, False,
         True],
       [ True,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False]])

In [45]:
z[z<5]

array([4, 1, 2, 3, 2, 3, 4, 1, 4, 3, 3, 4, 2, 1, 1, 2, 3, 1, 1, 2, 1, 2,
       2, 1, 1, 2, 1, 4, 3, 4, 2, 3, 3, 1, 4, 3, 4, 1, 4, 2, 1, 3, 4, 1,
       4, 2, 1, 2, 3, 2, 2, 2, 2, 4])

In [49]:
z[z<3].sum()

47

In [47]:
z[(z>=3) & (z <=6)]

array([6, 4, 3, 6, 3, 4, 4, 3, 3, 6, 4, 6, 5, 5, 3, 6, 5, 6, 4, 3, 4, 3,
       3, 5, 4, 3, 4, 4, 3, 6, 4, 5, 4, 5, 3, 5, 6, 6, 4, 6, 5, 6])

In [48]:
np.random.rand?      #gives description of the functions in numpy

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method